# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConnectCli < Formula
  desc "CLI for the Connect platform — MCP client for AI agents"
  homepage "https://github.com/redpine-ai/connect-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.1.2/connect-cli_0.1.2_darwin_amd64.tar.gz"
      sha256 "7cd22188f48d3b0d4d43b840b987901c0f8c2db8ec31df775453fc7b2d13953e"

      define_method(:install) do
        bin.install "connect"

        output = Utils.safe_popen_read(bin/"connect", "completion", "bash")
        (bash_completion/"connect").write output
        output = Utils.safe_popen_read(bin/"connect", "completion", "zsh")
        (zsh_completion/"_connect").write output
        output = Utils.safe_popen_read(bin/"connect", "completion", "fish")
        (fish_completion/"connect.fish").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.1.2/connect-cli_0.1.2_darwin_arm64.tar.gz"
      sha256 "51325e297e7dcde10b7e267d146f4a72e2630a508ab397176c245d28bfbc1a82"

      define_method(:install) do
        bin.install "connect"

        output = Utils.safe_popen_read(bin/"connect", "completion", "bash")
        (bash_completion/"connect").write output
        output = Utils.safe_popen_read(bin/"connect", "completion", "zsh")
        (zsh_completion/"_connect").write output
        output = Utils.safe_popen_read(bin/"connect", "completion", "fish")
        (fish_completion/"connect.fish").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.1.2/connect-cli_0.1.2_linux_amd64.tar.gz"
      sha256 "ab9c044c12c4c2ba89c79ee8191e82ce6c2a1c3536a3af1fac23131d8c1c4a08"
      define_method(:install) do
        bin.install "connect"

        output = Utils.safe_popen_read(bin/"connect", "completion", "bash")
        (bash_completion/"connect").write output
        output = Utils.safe_popen_read(bin/"connect", "completion", "zsh")
        (zsh_completion/"_connect").write output
        output = Utils.safe_popen_read(bin/"connect", "completion", "fish")
        (fish_completion/"connect.fish").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.1.2/connect-cli_0.1.2_linux_arm64.tar.gz"
      sha256 "641152b818c4d9ab18e2d74de557b11c28c0c9ad511c26058e9e795416e9697a"
      define_method(:install) do
        bin.install "connect"

        output = Utils.safe_popen_read(bin/"connect", "completion", "bash")
        (bash_completion/"connect").write output
        output = Utils.safe_popen_read(bin/"connect", "completion", "zsh")
        (zsh_completion/"_connect").write output
        output = Utils.safe_popen_read(bin/"connect", "completion", "fish")
        (fish_completion/"connect.fish").write output
      end
    end
  end
end
