# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConnectCli < Formula
  desc "CLI for the Connect platform — MCP client for AI agents"
  homepage "https://github.com/redpine-ai/connect-cli"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.0.3/connect-cli_0.0.3_darwin_amd64.tar.gz"
      sha256 "0e0de83aed1a5b88683c465a4b8782c9a56c51bdf59ecfc2c1a2ceaaaa240247"

      define_method(:install) do
        bin.install "redpine"

        output = Utils.safe_popen_read(bin/"redpine", "completion", "bash")
        (bash_completion/"redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "zsh")
        (zsh_completion/"_redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "fish")
        (fish_completion/"redpine.fish").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.0.3/connect-cli_0.0.3_darwin_arm64.tar.gz"
      sha256 "6717375286291b1efc65530cad09629aad26f9899d413fb20ea57f2725fe8451"

      define_method(:install) do
        bin.install "redpine"

        output = Utils.safe_popen_read(bin/"redpine", "completion", "bash")
        (bash_completion/"redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "zsh")
        (zsh_completion/"_redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "fish")
        (fish_completion/"redpine.fish").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.0.3/connect-cli_0.0.3_linux_amd64.tar.gz"
      sha256 "6b1bb5ca186dad1327accc538009ed0c8ddffb7337874aca40304c04d2a84a68"
      define_method(:install) do
        bin.install "redpine"

        output = Utils.safe_popen_read(bin/"redpine", "completion", "bash")
        (bash_completion/"redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "zsh")
        (zsh_completion/"_redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "fish")
        (fish_completion/"redpine.fish").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.0.3/connect-cli_0.0.3_linux_arm64.tar.gz"
      sha256 "62fdf101325bc2b8fcdea93b8fac611b29cf22889815942305a89de9c1fe6acd"
      define_method(:install) do
        bin.install "redpine"

        output = Utils.safe_popen_read(bin/"redpine", "completion", "bash")
        (bash_completion/"redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "zsh")
        (zsh_completion/"_redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "fish")
        (fish_completion/"redpine.fish").write output
      end
    end
  end
end
