# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConnectCli < Formula
  desc "CLI for the Connect platform — MCP client for AI agents"
  homepage "https://github.com/redpine-ai/connect-cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.0.1/connect-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "3f79aeec9b03f4a26f6fac0cac3d7bf3b5b21c06aeeb4c14d517c13053ab4b74"

      define_method(:install) do
        bin.install "redpine"

        output = Utils.safe_popen_read(bin/"redpine", "completion", "bash")
        (bash_completion/"redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "zsh")
        (zsh_completion/"_redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "fish")
        (fish_completion/"redpine.fish").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.0.1/connect-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "2174e00cfcf09f89992ccc7ce72c61ecb29f2410f7144e508adba74a5525fe3b"

      define_method(:install) do
        bin.install "redpine"

        output = Utils.safe_popen_read(bin/"redpine", "completion", "bash")
        (bash_completion/"redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "zsh")
        (zsh_completion/"_redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "fish")
        (fish_completion/"redpine.fish").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.0.1/connect-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "5f3eba04d73af42628429c481068b9502511e4a9d70907dcf5cb686593ce1f5e"
      define_method(:install) do
        bin.install "redpine"

        output = Utils.safe_popen_read(bin/"redpine", "completion", "bash")
        (bash_completion/"redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "zsh")
        (zsh_completion/"_redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "fish")
        (fish_completion/"redpine.fish").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redpine-ai/connect-cli/releases/download/v0.0.1/connect-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "872cc02b6b8a74f871a0b720a01c92590fa3adf94915ee28403d1dc242010757"
      define_method(:install) do
        bin.install "redpine"

        output = Utils.safe_popen_read(bin/"redpine", "completion", "bash")
        (bash_completion/"redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "zsh")
        (zsh_completion/"_redpine").write output
        output = Utils.safe_popen_read(bin/"redpine", "completion", "fish")
        (fish_completion/"redpine.fish").write output
      end
    end
  end
end
